server {
    listen 80;
    server_name odinn.site www.odinn.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        # chỉ bật lần đầu tiên để đăng kí https
        return 200 "Nginx is running for certbot\n";
        add_header Content-Type text/plain;
    }

    # location / {
    #     return 301 https://$host$request_uri;
    # }
}

# server {
#     listen 443 ssl;
#     server_name odinn.site www.odinn.site;

#     ssl_certificate /etc/letsencrypt/live/odinn.site/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/odinn.site/privkey.pem;

#     location /api {
#         root /var/www/backend/public;
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         root /var/www/backend/public;
#         fastcgi_pass backend:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }

#     location / {
#         proxy_pass https://admin:5173;
#         proxy_ssl_verify off;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }